language: node_js
node_js:
  - '5.6'

before_install:
  - npm install -g bower
  - npm install -g gulp

script:
  - npm install
  - bower install
  - gulp vet

notifications:
  email:
    - jeevan@jeevanjames.com